### ISSUE TITLE
BE / FE : duplicate entry

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#109]
stop page from erroring out if email for provider or admin already exists and instead send an alert to the FE

**Comment by justwheel** [comment]
@ldidonato Could you please explain this one in more detail? We looked at it in the back-end meeting but weren't sure what page you were using or what the error was.

**Comment by ldidonato** [comment]
@jwflory it happens when you try to make an admin with an email that already exists in the db, or a provider with the email already taken.

**Comment by ldidonato** [comment]
![Screen Shot 2019-10-31 at 8 50 26 AM](https://user-images.githubusercontent.com/10453584/67948151-8b895480-fbbb-11e9-883d-3db8ebf68872.png)

**Comment by ldidonato** [comment]
very big very important issue

**Comment by leong96** [comment]
Oh, this is during registration! The back end team was puzzled because we thought this was during login (which wouldn’t make sense). Yup, this needs fixing.

**Comment by R-Eli-Levasseur** [comment]
Bug fixed, added feedback to page if duplicate is found as well

**Comment by justwheel** [comment]
@eguy006 Was this fixed by PR #148?
