### ISSUE TITLE
BE Story: Changing Provider Name causes events to disappear until page is reloaded

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#113]
# Steps to Duplicate

- Login as a provider
- Click settings 
- Click Change Name
- Hit Save, causing the page to reload

the name of the provider does not change to the new name until page is reloaded again, events in the table disappear until the page is reloaded as well

**Comment by nlMeminger** [comment]
Does this affect events showing up in search at all?

**Comment by nlMeminger** [comment]
confirmed, does affect the search index.  Need to make a call to rebuild the index

This is probably causing @ldidonato 's issue because the page is looking for events owned by the old name before it is reloaded.

**Comment by R-Eli-Levasseur** [comment]
Fixed this bug

**Comment by justwheel** [comment]
Fixed in #148.
