### ISSUE TITLE
FE Story: add approve/deny buttons to event page when pending

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#114]
# Summary

Add approve/deny buttons to event page

# Background

It is annoying for an admin to click view an event and the have to go back and find it again in the list.  Having approve deny buttons in the event page would help.

# Details
When the admin is authenticated and when an event is pending, approve/deny buttons should be at the top of the page. after approving, it should redirect the admin back to the admin portal

**Comment by justwheel** [comment]
Discussed in back-end meeting. This is a nice idea, but it is a nice-to-have feature. I targeted it for Sprint 5 if we have enough time to get this.

**Comment by justwheel** [comment]
I revisited this again with @leong96 to get a back-end perspective. Unfortunately there is not enough time left in the project to implement this feature. I'm closing this issue as wontfix for the time being. :clapper:
