### ISSUE TITLE
FE Story:  add feedback for rejected events

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#115]
# Summary

When an event is rejected, it is unhelpful to not know why it was rejected.  So when the deny button is clicked, a modal should show up asking for a reason/feedback as to why it was denied.

# Outcome

When an event is denied, feedback should be submitted.  Then it should show up on the provider portal as rejcted and a link to view comments which could probably be in a  modal

**Comment by leong96** [comment]
Going to add myself to this, because the email will need to contain the reason for the rejection.

**Comment by justwheel** [comment]
@leong96 Okay, that's fine. Remember this is a backlog / nice-to-have feature though. Figuring out email templates more broadly for #134 is more important than adding an approval/rejection feedback. 1-on-1 email from a GRASA admin to a provider is a system that already exists for GRASA to meet this requirement.

**Comment by ldidonato** [comment]
FE done in "deny-popups" branch

**Comment by justwheel** [comment]
@ldidonato Is the branch ready for a pull request?

**Comment by leong96** [comment]
@jwflory Not just yet there, I still need to implement the back end portion, which is my plan for tomorrow.

**Comment by justwheel** [comment]
This was closed by #206. Closing as complete. :clapper:
