### ISSUE TITLE
 add modal to password reset page

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#119]
# Summary

On the reset password page where the user submits their email address, if we were to check if that email exists in our db, then we would be exposing what emails are actually in our db potentially.  But we still need some kind of feedback for the user, so I suggest adding a modal after the email is submitted that says something along the lines of "If the email address provided matches any of our records, we will send a reset link to it" or something better sounding.  Any comments here would be appreciated by @ldidonato or @leong96

**Comment by ldidonato** [comment]
I only agree to an extent, there are some sacrifices that need to be made for UX. Many websites I've done reset password on have given me the "email address is not associated with an account" message when I've made typos. But if you feel very strongly about this we can rephrase that message to something like "Sending reset link to that account if it exists", so something less technical.

**Comment by nlMeminger** [comment]
My worry is someone spamming our system inputting addresses to see if they exist in the db or not.  Do I actually expect this to happen? Probably not.  But I think its something we should consider.  @jwflory any thoughts here?

**Comment by leong96** [comment]
To comment on @ldidonato's point, it is certainly possible to check whether an email is associated with an account; the logic is already kind of in there as well: if the account exists, the page will take a bit longer to reload post-submit (due to the email sending), if the email is not associated, then the reload is instant. We can just stick a message/modal in there as well with the appropriate message.

**Comment by nlMeminger** [comment]
We should only be sending the email if the account exists, but we should not be telling the user if the acount exists or not is my point.

**Comment by leong96** [comment]
Reread what you wrote, I get it now. So show a blanket message for everyone going "If this email exists, we've sent an email to it", without specifically saying whether an email was actually sent.

**Comment by nlMeminger** [comment]
correct.

**Comment by justwheel** [comment]
Let's revisit this in Sprint 5 planning. There is a lot on the back-end plate for the next two weeks, so we need to protect time for highest-priority tasks.

**Comment by leong96** [comment]
There is now a message indicating that an email will be sent if a user exists. This is displayed no matter what is inputted into the field.

**Comment by justwheel** [comment]
This was closed by #173. Thanks @leong96! Closing as complete. :clapper:
