### ISSUE TITLE
Create configuration file

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#12]
# Summary

There are a number of variables spread across this project that would be best abstracted out into a single YAML file at the root of the project, such as db password and username, allowed hosts, project name, etc

# Details

ideally, we would use a YAML file and add code into the relevant places to read in the variables using the python YAML library

# Outcome

All of our system-wide variables such as passwords or hosts or search tags should be in a single location that is easy to edit.

**Comment by justwheel** [comment]
See #66.
