### ISSUE TITLE
BE Story: Clean up codebase for hand-off

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#123]
# Summary

Some files are very large, and not everything in them all relate to each other.  We can refactor some things and make separate files for separate sets of features to improve the readability of the code.

**Comment by justwheel** [comment]
I will take this issue on for Sprint 5, Week 2. My PR, #164, is part of this work. Black is a tool based on the [PEP-8 Style Guide](https://www.python.org/dev/peps/pep-0008/) of writing Python code, with some opinionated differences Black developers believe make Python code easier to read.

This is mostly cosmetic changes to layout and overall code structure (not changing functionality). While it seems trivial and maybe a little annoying to have style dictated by a linter, it helps unify our different coding styles together and makes it easier for the future maintainers, Monroe County, to understand our code base more easily.
