### ISSUE TITLE
BE Story: Add rebuild_index functionality to special cases

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#126]
# Summary

After an event edit is made, or a provider name is changed, the whooch index needs to be updated

**Comment by justwheel** [comment]
@nlMeminger Are you currently working on this?

**Comment by nlMeminger** [comment]
Yes

**Comment by justwheel** [comment]
Changing provider name rebuilds the search index per @eguy006 in #148. After an event edit is still needed.

**Comment by justwheel** [comment]
The remaining piece of this issue was moved to #154. Closing this issue as complete! :clapper:
