### ISSUE TITLE
Changing Organization Name does not escape SQL characters

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#129]
# Summary

Changing the organization name with certain characters can cause a database error

## Stacktrace

```
Request Method: | POST
-- | --
http://grasa.larrimore.de/provider.php
2.2.6
ProgrammingError
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's House' WHERE `org_name` = 'Cat Mafia'' at line 1")
/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py in query, line 226
/usr/local/bin/python3
3.6.9
['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/app/grasa_event_locator',  '/app/apps',  '/app/libs']
Wed, 30 Oct 2019 13:29:59 -0400
```

# Affected components

- [ ] Authentication
- [ ] Event curation system
- [ ] Search
- [ ] Admin portal
- [X] Other (explain below)

User profiles

# Suggested fix

Might be a hard-coded SQL query somewhere? Doesn't seem to affect creating organizations, only changing their name.

Refactor all `cursor.execute` statements.

**Comment by R-Eli-Levasseur** [comment]
Refactored everywhere I saw it
