### ISSUE TITLE
BE Story: Admins delete events

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#131]
# Summary

Admins can delete an event from the web application

# Background

An administrator may need to remove an event if it no longer exists and the provider is not responsive. Or if there are other logistical issues with the event taking place. This helps the administrator manage the published events over time and maintain an accurate database.

# Details

This needs to be reviewed by a back-end team member for estimated amount of work/time required to implement this. It is an important feature but it is untracked in our Project Success Matrix.

# Outcome

Administrator users have full privileges to maintain a record of events in the database (e.g. deleting old, retired, or inactive events)

**Comment by leong96** [comment]
The delete button on the all events page as well as the delete modal are already present. This will not take much work, Eli's approve/deny pages can serve as the basis for a delete function quite easily.

**Comment by R-Eli-Levasseur** [comment]
Implemented

**Comment by justwheel** [comment]
@eguy006 Was this implemented by PR #148?
