### ISSUE TITLE
Ops Story: Write an automated install script

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#133]
# Summary

Write a one-shot install script to run an initial installation of the application

# Background

When we pass this application to Monroe County IT, a one-shot script to install the application for the first time on a CentOS 7.x host will help them get started running our application. We briefly discussed not wanting to use Docker Compose for this; since we are not testing any other install methods, we should ensure there is time to adequately test the install script before the hand-off.

# Details

During the 2019-11-13 ops meeting, we agreed that a setup/install script should do three things:

- Start container
- Stop container
- Build container/run migrations

We sub-divided each one into a checklist of minimum functionality below:

### Base

- [x] Include argument handling for up to one _optional_ flag (for port)

### Start container

- [x] `docker run -it grasa/event-locator`
- [x] `docker exec -it container/label python3 manage.py rebuild_index`

### Stop container

- [x] `docker stop -t grasa/event-locator`

### Setup container

- [x] `docker build -t grasa/event-locator .`
- [x] `docker exec -it grasa/event-locator python3 manage.py migrate`

# Outcome

Monroe County IT has a straightforward way to get an initial install of the application up and running; how they choose to manage it beyond that is up to them

**Comment by justwheel** [comment]
_Discussed in 2019-11-13 ops meeting with @nlMeminger and @jwflory._

---

@nlMeminger and I white-boarded this one out. I summarized our discussions into small, concrete steps in the _Details_ section of the original ticket. @nlMeminger, please double-check the checklist and make sure this looks right. :+1: 

![Picture of whiteboard planning notes for initial install script](https://user-images.githubusercontent.com/4721034/68799413-1ccde180-0626-11ea-8e6d-b7b58248e04a.jpg "Picture of whiteboard planning notes for initial install script")

**Comment by justwheel** [comment]
Mostly done in #226, but keeping this issue open for additional polish and refactoring.

**Comment by nlMeminger** [comment]
This was finished in #242 @jwflory good to close?

**Comment by justwheel** [comment]
Just approved #242. This is good to close, thanks for following up here @nlMeminger. :+1:
