### ISSUE TITLE
BE Story: Finish integrating email functionality

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#134]
# Summary

Finish integrating the working email functionality into other parts of our app that need to send emails

# Background

Email was introduced into the application previously (see #37, #117, #121 for more info). Now, we need to finish integrating the email function across our app. In the last back-end meeting, we walked through the application to think about what areas are left to plug in.

# Details

We need to figure out a way to store message templates as a text file for each of the events below:

- [x] Reset account password
- [x] Notification for alternate contact
- [x] ~~@leong96 + @jwflory — Event status change (e.g. user account approval/denial, event approval/denail for new events and edited events)~~ #201
- [x] Changing account email
- [x] Invite Provider
- [x] Create Admin
- [x] ~~@jwflory — Templates / storing messages~~ #201

# Outcome

Important information and changes in the application are sent via email

**Comment by leong96** [comment]
#145 Implements the main email functionality, however, the template system is still being researched.

**Comment by justwheel** [comment]
I think we want something like this for templates:

https://docs.djangoproject.com/en/2.2/topics/templates/#django.template.loader.render_to_string

**Comment by justwheel** [comment]
#201 will close this issue. All remaining functionality implemented.

**Comment by leong96** [comment]
This does indeed close this issue. Tangentially, #115 has some modals whose inputs will be added to the emails, but that can be addressed over there.
