### ISSUE TITLE
BE Story: Research ordering of search results

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#155]
# Summary

Research how difficult / how much work is required to change order of search results

# Background

Previously we talked about changing the sort order of search results in the interface. Obviously they are filtered by keywords, but what about after that? We mentioned alphabetical sort and sorting by date of event creation (most recent sorted ahead of oldest). This needs further discussion after a technical feasibility review.

# Details

The deliverable for this ticket is a comment on this GitHub issue summarizing a next plan of action for ordering the search results. If it's not viable, please explain why. If it is viable, briefly explain what work is needed.

# Outcome

Implement user feedback collected by @leiyinmon to improve search experience

**Comment by R-Eli-Levasseur** [comment]
Check this later
https://django-haystack.readthedocs.io/en/v2.4.1/searchqueryset_api.html?highlight=sort#SearchQuerySet.order_by

**Comment by R-Eli-Levasseur** [comment]
Grasa wants sorted by alphabetical descending on event title

**Comment by R-Eli-Levasseur** [comment]
Has been implemented

**Comment by justwheel** [comment]
Implemented by #237.
