### ISSUE TITLE
Formatting descriptions

### ISSUE THREAD

**Issue by R-Eli-Levasseur** [jwflory/django-rit-grasa#197]
Currently event descriptions do not carry over formatting, so if I enter a list like:
Things:
- Thing 1
- Thing 2
It will display on event page as:
Things: - Thing 1 - Thing 2

**Comment by nlMeminger** [comment]
can we encode with html and just store that?

**Comment by justwheel** [comment]
@R-Eli-Levasseur Where is the event description not being carried over from? The database?

@ldidonato Is this something you can take a look at or is it a back-end issue?

**Comment by justwheel** [comment]
We covered it in the back-end meeting. Here is a screenshot of the list formatting breaking:

![Screenshot of event text with missing new lines](https://user-images.githubusercontent.com/4721034/68804957-ddf15900-0630-11ea-89cc-26335019c10c.png)

**Comment by R-Eli-Levasseur** [comment]
![image](https://user-images.githubusercontent.com/9360433/69458406-3addc500-0d3d-11ea-9a26-9bb291f12478.png)
Got it working with cases I could think of

**Comment by leong96** [comment]
![image](https://user-images.githubusercontent.com/8702682/69474033-33dca400-0d89-11ea-8332-21477a298de5.png)
What more could a person ask for?
Approved.

**Comment by justwheel** [comment]
Implemented by #236.
