### ISSUE TITLE
BE Story: Don't send email if address is the same.

### ISSUE THREAD

**Issue by leong96** [jwflory/django-rit-grasa#198]
# Summary

Write an if statement that checks whether the inputted username when changing it matches the current one.

# Background

Emails are sent even if the user decides to leave their username the same.

# Details

If statement: check whether the inputted email equals the user's email. If they are the same, do not send the email.

# Outcome

No email is sent.

**Comment by justwheel** [comment]
Addressed by #207. Closing as complete. :ocean:
