### ISSUE TITLE
Add config for contact email

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#222]
add a config so the help pieces don't say "johndoes@email.com" and grasa can configure it
Locations that have it:

./grasa_event_locator/templates/register.html:110:                                          <p>More Questions? Please contact us at <a href="mailto:johndoe@email.com">johndoe@email.com</a></p>

./grasa_event_locator/templates/provider.html:95:                                          <p>More Questions? Please contact us at <a href="mailto:johndoe@email.com">johndoe@email.com</a></p>

ALSO:
add a confiq for MapQuest API key

used here:
createEvent.html line 383
editEvent.html line 395

**Comment by justwheel** [comment]
In progress, have the contact email done but still working on MapQuest piece. Will try to finish before back-end meeting.
