### ISSUE TITLE
Add dependencies for search to docker

### ISSUE THREAD

**Issue by R-Eli-Levasseur** [jwflory/django-rit-grasa#30]
# Summary

Add dependencies for search to docker

# Background

These pip installs need to be done and rebuild_index must be called on startup

# Details

These commands: 
pip install django-haystack
pip install whoosh
manage.py rebuild_index

# Outcome

search so far will work

**Comment by nlMeminger** [comment]
What is the purpose of the  manage.py rebuild_index command?

**Comment by R-Eli-Levasseur** [comment]
The purpose is that it writes the whoosh index file, which is basically how whoosh searches. You have to run rebuild_index the first time to generate an index of EVERYTHING, then once that's done you run update_index whenever you want to update the index with newly add events

**Comment by nlMeminger** [comment]
So then in terms of the containers building, when do those commands need to
run?

**Comment by R-Eli-Levasseur** [comment]
rebuild_index should probably be called right before runserver when booting the containers

**Comment by nlMeminger** [comment]
Good to know, thank you. Do you have specific versions of the packages
you’d like?

**Comment by R-Eli-Levasseur** [comment]
Not in particular

**Comment by nlMeminger** [comment]
latest it is!

**Comment by nlMeminger** [comment]
resolved in #32
