### ISSUE TITLE
Add an email function to the projet

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#37]
# Summary
We need to add a way for the app the send emails

# Background
There are a couple reasons we need this, most notably being recover password, and sending program update emails.

# Outcome

The app should be able to send an email to a user when needed.

**Comment by justwheel** [comment]
@nlMeminger found a set of email wrappers around Python standard libraries in the Django library:

https://docs.djangoproject.com/en/2.2/topics/email/

It's likely we'll use this for email.

**Comment by justwheel** [comment]
@leong96 took the lead on email during Sprint 4, see #117 and #121 for more details. Closing as complete. :clapper:
