### ISSUE TITLE
Update Pipfile with static version numbers for dependencies

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#38]
# Summary

It is best to have version numbers than just "*"

# Details

Need to find what versions are currently out there for our dependencies, and lock our Pipfile on then

# Outcome

We should have static version numbers for all dependencies

**Comment by justwheel** [comment]
@nlMeminger Is it possible to get a PR for this over the weekend?

**Comment by nlMeminger** [comment]
Aye aye captain
