### ISSUE TITLE
Ensure app starts successfully on initial run

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#39]
# Summary

Make sure that when the app runs for the first time, it starts up successfully without errors

# Background

Current problem is that certain database initialization is not happening. For a fresh install or dev environment, the migrations need to be run for the app to start. It's not clear if the migrations are needed or what the best way to initialize the database for our project.

# Details

1. Do we need any of the existing migrations that were automatically created? If not, delete them and see what happens. (If it works after this, we're done!)
2. Research into the best way to initialize a state for a MySQL DB used in Django (write our own init script? trigger initialization in Django?)
3. Ship a script to initialize the database, needs to be manually run in DB Docker container or manually on a prod server before Django starts up

# Outcome

* Anyone can grab our project and run it locally without problems
* Helps us later for final deployment when we (or Monroe County IT) sets this up for the first time

**Comment by nlMeminger** [comment]
this is fixed.
