### ISSUE TITLE
Create persistent database for development and testing

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#40]
# Summary

Make a persistent database available for local development and a common testing environment

# Background

We need persistent databases for local development and for a common testing server. Persistent database for development means working volumes for the Docker container. Testing database for staging means actual hosted database, not running in a container.

# Details

@nlMeminger is going to submit a PR with the volumes for the database container (using a local directory added to `gitignore`). He is also going to stand up a database server to use with a hosted version of the application. This will be used for a common testing environment for the whole team.

# Outcome

* **Local dev**: Don't need to create events / users from scratch again
* **Testing env**: Common database for the whole team to use for testing (and showing off to the world)

**Comment by nlMeminger** [comment]
The hosted staging database is blocked on the config file in #12

**Comment by nlMeminger** [comment]
The dev environment is taken care of in b97e8264c4e2322c282f4dd4bd7ea569d0e19a18

**Comment by justwheel** [comment]
@nlMeminger Thanks for working on this. :+1: 

Will the database container be able to write the database files to the local directory? It isn't clear to me if the volume is mounted into a place where the MySQL container writes data to the volume:

https://github.com/jwflory/django-rit-grasa/blob/b97e8264c4e2322c282f4dd4bd7ea569d0e19a18/docker-compose.yml#L16-L17

If you can take a look at that one part, it would be great to get this in as a PR to `master` when you have a chance! :+1:

**Comment by nlMeminger** [comment]
This is done.
