### ISSUE TITLE
Merge default home page with search page

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#42]
# Summary

Merge existing search page into the default landing page

# Background

Currently the default landing page of the app is not configured and gives an error (i.e. loading `http://localhost:8000/` in browser). The page at `index.php` is our intended landing page. We need to integrate the following three "pages" into one:

1. `index.php`
2. `search.html`
3. Set up a default route for app landing page (i.e. `localhost:8000/`)

# Details

This makes our most important functionality (i.e. search) at the most obvious location for our app: the home page. It also will fix the issue of testing the local development site, since to a newcomer, it would appear the site is broken if you only hit the root URL.

# Outcome

* Less confusing about where working search is
* Helpful for user testing to use our actual search functionality

**Comment by nlMeminger** [comment]
any movement on this @eguy006

**Comment by justwheel** [comment]
Moved to Sprint 4. :running_woman: :four: :running_man:

**Comment by nlMeminger** [comment]
I think this one is completed.  any comments anyone?

**Comment by justwheel** [comment]
@eguy006 got this one previously. Closing as complete. :clapper:
