### ISSUE TITLE
Add filters to search results

### ISSUE THREAD

**Issue by R-Eli-Levasseur** [jwflory/django-rit-grasa#43]
# Summary

Get the search to a point where it works seamlessly with our filters 

# Background

The search currently only functions for keywords, so we still need to implement features #17, #18, and #19 on our success matrix. This would be filtering by categories and by zip code (possibly also municipality)

# Details

Not positive how to get around the issues discovered last week while developing search, so I'm getting help from Justin on Friday to go over the code and discuss.

# Outcome

All search functionality (except #20) implemented

**Comment by justwheel** [comment]
@eguy006 Could you please link some of the docs you are working with for Whoosh/Haystack? Or anything you think it would be helpful for me to review before we meet in person? I haven't looked into it in depth much yet, but I will try to prime myself before our Friday meeting.

**Comment by justwheel** [comment]
@eguy006 Do you think it's good to call this one completed by #49?

**Comment by justwheel** [comment]
Checked in with @eguy006 in the back-end meeting and we agreed this issue was completed by #49. Closing as complete. :clapper: 

Nice work @eguy006. :+1:
