### ISSUE TITLE
User Input Error Handling

### ISSUE THREAD

**Issue by leong96** [jwflory/django-rit-grasa#44]
# Summary

Messages to the user must be provided when incorrect input is given.

# Background

We have not yet considered the possibility of someone entering the wrong password or attempting to register with the email address of an existing user. At present, the form usually is either considered accepted, or the user is returned to the form, with no indication of why nothing happened.

# Details

The user should be given the appropriate feedback. The front-end would be tasked with providing the message indicating that say, the password was incorrect. The back-end would be tasked with implementing the message within the existing Python syntax.

# Outcome

Anywhere where the user could enter invalid info that wasn't already handled by the front-end's validation, some sort of feedback should appear.

**Comment by justwheel** [comment]
@leong96 Thanks for opening this.

If I understand, this is different user input handling from what @ldidonato did in the event creation form, but specifically around user account registration / login. @leong96 or @ldidonato, if you have thoughts on how to implement this, keep us up-to-date in this ticket please. :slightly_smiling_face: 

If you get stuck on technical implementation and want to bounce ideas, let's chat in `#backend` on Slack.

**Comment by nlMeminger** [comment]
any movement on this?

**Comment by leong96** [comment]
A fair amount of this is actually complete. I’d need a close look and determine if every possible scenario is covered.

**Comment by justwheel** [comment]
I believe the remaining work for this (i.e. registering an account with an email that already exists) was done in #148. Since most of the work for this issue is done and the last little bit is in an open PR, I'm closing this issue as complete. :clapper:
