### ISSUE TITLE
Create basics of event curation system

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#5]
# Summary

Create the following parts of event curation system:

- [ ] Submission form (for providers)
- [ ] Admin access view for all events in database (including pending review and accepted events)

# Background

This feature involves working with the following parts:

* DB access:
    * GET: Get all events in database
    * POST: Submit event to database
* Forms: Collect user input

# Details

The [Django admin site](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/) is likely the most Django-friendly way to handle the event curation system. Each event can be created and managed within the admin panel. An example is [here](https://pagure.io/fedora-commops/fedora-happiness-packets/blob/master/f/happinesspackets/messaging/admin.py).

Forms are needed to collect data from user input in the front-end and post the user input to the database. See the [forms documentation](https://docs.djangoproject.com/en/2.2/topics/forms/) for more details. There is also [this Django Girls tutorial](https://tutorial.djangogirls.org/en/django_forms/).

# Outcome

* Authenticated user can submit events to system
* Admin user can view all submitted events in any state (e.g. pending and accepted)

**Comment by justwheel** [comment]
@leong96 Feel free to edit this / add anything else as needed.

**Comment by leong96** [comment]
Progress as of 9/23 is as follows:
- Now able to use POST to write entries to a database.

Still need to do:
- Learn how to retrieve entries from a database to display on a website. This will likely be accomplished with a for loop to get multiple events, then writing a variable to the webpage.

**Comment by justwheel** [comment]
@leong96 Thanks for the progress update.

> Learn how to retrieve entries from a database to display on a website. This will likely be accomplished with a for loop to get multiple events, then writing a variable to the webpage.

We probably need getter methods to retrieve a value from the database and yield the value as the `return`. This way, we can call an internal method for making a database query once anywhere in the application, versus repeating the same database code multiple times across the repo.

For example, this idea is expressed below in the simplest of pseudo-code:

```python
def get_db_event_title(event_id):
    event_title = some_mysql_library.query("SELECT event_title WHERE event_id_num = " + event_id)
    return event_title
```

We would have methods like this but for any data that we want to "inject" into the front-end. Does this explanation make sense?

**Comment by leong96** [comment]
It does, yes.

**Comment by nlMeminger** [comment]
I would probably call this complete given we are now at beta.  @jwflory what do you think?

**Comment by justwheel** [comment]
+1. Given we passed the beta review, I think we have the basics of the event curation system in place. Closing. :clapper:
