### ISSUE TITLE
Double Login

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#51]
# Summary

Gets a forbidden page when you try to login as provider when you are already logged in as admin

**Comment by nlMeminger** [comment]
Ideally we would want any attempt to login while already authenticated to
just redirect you to your own portal

**Comment by justwheel** [comment]
Could someone please help me understand this bug? It doesn't make sense to me that an admin would try to log in as a provider. At what point is an admin prompted to log in as a provider?

**Comment by justwheel** [comment]
Briefly discussed in back-end meeting. @leong96 knows how to fix this one by redirecting the login if you are already logged in.

**Comment by leong96** [comment]
Seemed that the login page was already set to go to index.php if the user was authenticated. There is now a pull request to switch this to the search page (#132). Let's see what happens.

**Comment by justwheel** [comment]
This was fixed by #132. Closing as complete. :clapper:
