### ISSUE TITLE
Research estimated cost for MapQuest API pricing and plans

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#59]
# Summary

Research and estimate cost possibilities for using MapQuest API

# Background

We are committed to using the MapQuest API for geocoding latitude and longitude in our application. After looking at the [pricing and plans](https://business.mapquest.com/pricing-plans/), there may be a cost for this beyond 15,000 transactions a month. It's unlikely the application will hit this threshold on launch, but it is a cost worth documenting and estimating.

# Details

In Sprint 4 or 5, circle back around to the search functionality, see how we are caching geocoded data, if at all. Based on current usage by next gate review, I'll give a best estimate.

# Outcome

Sponsor is aware of potential cost factor if applications grows/scales

**Comment by nlMeminger** [comment]
@jwflory  how is this going?

**Comment by justwheel** [comment]
## Third-party service costs (fixed)

* `>`15,000 lookups per month: **Free**
* 15,001-30,000 lookups per month: **$99/month**
* 30,001-75,000 lookups per month: **$199/month**

## Estimated cost

Assume an average search takes, on average, four lookups to the MapQuest API. This allows for approximately 3,750 free searches before GRASA/Monroe County would cross the free threshold.

With this number in mind, I'm closing this issue as complete. :clapper:

**Comment by justwheel** [comment]
@ldidonato noted my calculations were wrong! After recent changes to our projecxt, the MapQuest API look-ups only happen once when adding a new event. In other words, the application can support up to 15,000 new _events_ per month. There is no location filter for search, so no look-up will happen in the search interface.
