### ISSUE TITLE
Manage user accounts in database

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#6]
# Summary

Manage three tiers of user relationships (admins, providers, non-users) in database and create database schema defined in Django app

# Background

In the back-end meetings, we concluded that user permissions are divided in three categories:

* **Non-users**:
    * Can only run program searches
    * No authentication required
* **Authenticated users**:
    * Manage account details / profile
    * Submit new programs/events
    * Edit their own programs/events
    * View all programs by their organization
* **Admin users**:
    * Approve/reject event submissions and edits
    * Manage accounts of other non-admin users
    * Change theming of site (i.e. logo and color scheme)
    * Edit any program/event
    * Delete/hide events
    * Invite new users with an email address [_nice to have_]

# Details

Best to start with [overview of authentication](https://docs.djangoproject.com/en/2.2/topics/auth/) in Django. Then look through the details of [User objects](https://docs.djangoproject.com/en/2.2/topics/auth/default/) to understand how users how constructed. Start thinking of how to map out our three levels of users above in the example. Note the existence of a superuser option.

# Outcome

* Different levels of access segmented out across different groups of users
* Other parts of back-end have a clear way to limit access based on clearance

**Comment by R-Eli-Levasseur** [comment]
Authentication has been difficult, the base Django authentication is not what we need so we have to substitute our own custom model which I have not figured out yet. I have changed our models to better fit our new requirements however, and have written (but not tested yet) most queries we will need for above functionality. i.e. Editing an event should just be models.Program.editProgram(), seeing all pending users for admin should just be models.User.get_all_pending()

**Comment by nlMeminger** [comment]
Could you please explain more why the base Django authentication is not
going to work for us?

**Comment by R-Eli-Levasseur** [comment]
Authentication was solved with extension of the base user class
