### ISSUE TITLE
Create instant/quick deployment project script for CI/CD

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#7]
# Summary

Create an automatic way to quickly deploy project changes (i.e. 15-30 minutes) to a staging / test environment

# Background

Setting up a quick and easy pathway to deploying software to a testing environment lets us get quick / immediate feedback on changes merged into `master` branch. Additionally, it also improves our ability to get early feedback from the sponsor and encourage them to be an active participant in the feedback process. Ultimately, it is a win-win for project development and demonstrating project progress on short notice.

# Details

There are two different ways I think of doing this. Choosing one option over the other depends on a confirmation of infrastructure by our sponsor.

### Automate container host for deploying as container

If a container deployment is preferred, the CentOS 7 VM needs to be set up with a container runtime. Instead of installing Docker and opening a security attack surface, we could use Podman and related tools to run rootless containers on CentOS 7 hosts.

In short, we create an automatic way to set up a CentOS 7 Podman host, and then figure out a way to get our container images pushed to the host for deploying.

### Write Ansible playbook to deploy on fresh CentOS 7 VM

If a container deployment is not used, the full installation of the app should be instrumented in an Ansible playbook. Different parts are done in different stages, e.g. database server set-up is done separately from app server set-up. Python+Django are installed on one VM, MariaDB on another, any load balancers elsewhere.

This is more challenging in some regards because we never get a perfect guarantee of what state our environment is in when we are deploying. At least, not like we do with a container image. However, we might also be trading off in simplicity of figuring out a container deployment mechanism when this might not be an option our sponsor can support either.

One blocker of this ticket is testing the waters to see how container-friendly our sponsor is.

# Outcome

* New development changes are visible on short notice
* Any developer can trigger site rebuild automatically (i.e. does not require one person to rebuild VM / deployment each time to pull new changes)

**Comment by nlMeminger** [comment]
I think for our development purposes we should use docker containers as a way to deploy to our team's infrastructure as it looks like that might be the simplest solution given our timeframe.  There exists a plugin for GitHub that can automatically make a docker image for us.  I would prefer this method as it would save the time of having to set up a clean VM every time we want to test, and can better guarantee our environment.  If the sponsor does not want to use containers for their final deployment it shouldn't be too difficult to hand them the code and its requirements so they can run bare metal if they want.

**Comment by justwheel** [comment]
@nlMeminger I am +1 to standardizing on containers, noting that final database deployment will likely not be hosted in a container.

For the purpose of standardizing with local development tools, what do you think of using docker-compose to orchestrate a Django container and a MySQL database container? Do we have enough time to set it up and use it vs. building only a Django container from a Dockerfile and hosting a MySQL database locally?

**Comment by nlMeminger** [comment]
Docker-compose with a container for the app and a container with MySQL
would probably be the easiest setup.

**Comment by justwheel** [comment]
See #11 with some helpful pieces with a first container and docker-compose file.

**Comment by justwheel** [comment]
A lot has changed since we originally started working on this. We now have a working Docker Compose script to build and run the application locally. @nlMeminger is creating a custom staging environment to pull and test new changes in a shared environment for the team (see #40).

Closing as complete. :clapper:
