### ISSUE TITLE
index.php error with empty database

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#72]
# Summary

With an empty db, index.php fails to load and gives this stack trace: 

Environment:
Request Method: GET
Request URL: http://localhost:8000/index.php
Django Version: 2.2.6
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'whoosh',
 'haystack',
 'grasa_event_locator']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
Traceback:
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/app/grasa_event_locator/views.py" in index
  279.         coord, e_id, title, address = zip(*zip_table)
Exception Type: ValueError at /index.php
Exception Value: not enough values to unpack (expected 4, got 0)

# Suggested fix

Add a try-catch if 0 events are returned

**Comment by leong96** [comment]
PR is now up to patch this.

**Comment by justwheel** [comment]
PR #85.
