### ISSUE TITLE
FE + BE: Hook up implemented FE pieces to working BE functionality

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#79]
## Provider Page

- [x] Change Email
- [x] Change Password
- [x] Are you sure? modal: FE piece
- [x] Delete Event 

## Edit Event

- [ ] ~some item’s don’t auto fill with info~ moved to #154
- [x] Hitting cancel from edit event is broken

## Admin Page

- [x] change email
- [x] change password

## View All Events Page

- [x] No data is hooked up
- [x] Delete event

## All Providers

- [x] Number of events

## All Admin

- [x] create admin isn’t working anymore, can’t test delete admin then

**Comment by justwheel** [comment]
Moved to Sprint 4. :running_woman: :four: :running_man: Also added @eguy006 since Harrison is focused on email integration.

**Comment by justwheel** [comment]
This was mostly done in #148. The last remaining piece was moved to its own issue, #154. Closing as complete. :clapper:
