### ISSUE TITLE
FE Story: Make no logo found image

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#80]
# Summary

Crate an image to be used in case the provider does not set a logo

# Background

# Details

# Outcome

**Comment by justwheel** [comment]
@ldidonato Do you think this is a Sprint 4 or Sprint 5 item?

Also we might want a view without a logo, in case the file upload functionality doesn't make it to the final product. We might not have any image for all organizations, so I prefer a responsive view without any images, if one is not set for the organization.

Does this make sense?

**Comment by justwheel** [comment]
Given that logo upload is not a feature that will make it to the final product, I am closing this issue. :clapper:
