### ISSUE TITLE
Make Login and Portal unaccessible while on mobile device

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#84]
# Front-End
FE can hide links in the header while in mobile

# Back-End
Needs to make the login and portal pages inaccessible by URL

**Comment by justwheel** [comment]
Moved to Sprint 4. :running_woman: :four: :running_man:

@eguy006 can help with this for Sprint 4. Alternatively, @nlMeminger was looking to pick up dev work, so this could be a good thing for him to look into if @eguy006 is approaching work limit for this sprint.

**Comment by ldidonato** [comment]
FE side is done

**Comment by justwheel** [comment]
Thanks @ldidonato! @eguy006, are the login and portal pages inaccessible by a URL? Is this something we have to do for the back-end? I'm trying to understand if this is necessary polish.

**Comment by justwheel** [comment]
@ldidonato @leiyinmon In the back-end meeting, we were wondering if the pages should be inaccessible, since we have mobile-friendly interfaces for the provider/admin pages. Is this issue completed?

**Comment by ldidonato** [comment]
The issue I had was even if the button isn't there the user can still go to /login.php in the browser and access the pages. I thought this was a BE thing with the routes or something. you can delete this issue if u want

**Comment by justwheel** [comment]
@ldidonato Thanks for clarifying! I think the work @leong96 is doing for #51 covers the back-end piece for this issue. I'm going to close this one as complete. :clapper:
