### ISSUE TITLE
FE & BE Story: add invite provider button

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#90]
# Summary

There should be a button in the admin portal on the allUsers page that lets an admin invite someone to create a provider account

# Details

On the all users page, there should be a button on the top that when clicked should show a modal with an email field only.  Then an email should be sent to the provider with a link to the registration page

# Outcome

Admins should be able to invite people to create provider accounts

**Comment by justwheel** [comment]
Moved to Sprint 4. :running_woman: :four: :running_man: 

Is this already implemented in the front-end? Whose work is in progress on this story?

**Comment by ldidonato** [comment]
FE piece is done

**Comment by nlMeminger** [comment]
🙌🙌

**Comment by justwheel** [comment]
Does it make more sense for @leong96 to work on this one since it is related to email?

**Comment by justwheel** [comment]
@leong96 is following up with @ldidonato on this after our back-end meeting.

**Comment by leong96** [comment]
#145 Establishes the base functionality email functionality. Will close this issue, as the template functionality to have a canned message for provider invites is a part of #134.
