### ISSUE TITLE
Map pins disappear after reload of search page

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#91]
# Summary

On first start of the app, all the pins for all the events in the db show up, but when I reload my page, they disappear

# Affected components

- [ ] Authentication
- [ ] Event curation system
- [x] Search
- [ ] Admin portal
- [ ] Other (explain below)

**Comment by justwheel** [comment]
@eguy006 @ldidonato Any ideas on this one?

**Comment by nlMeminger** [comment]
@eguy006 Could you put in those changes we made on the fly last week for this one?

**Comment by justwheel** [comment]
This is fixed in staging, I think because of @eguy006's #118. Closing as complete! :ocean:
